function [sMarket] = fMSCImarket(sCountryName)
%MSCI MARKET: Functions sorts whether the country is listet by the MSCI as
%emerging (EM) oder developed market (DM)
%   if-loop checking to which market the country belongs to using the
%   country name as described by Ball et al. (2016)
if isequal(sCountryName, "AUSTRALIA") || isequal(sCountryName, "AUSTRIA")...
   || isequal(sCountryName, "BELGIUM") || isequal(sCountryName, "CANADA")...
   || isequal(sCountryName, "DENMARK") || isequal(sCountryName, "FINLAND")...
   || isequal(sCountryName, "FRANCE") || isequal(sCountryName, "GERMANY")...
   || isequal(sCountryName, "GREATBRITAIN") || isequal(sCountryName, "HONGKONG")...
   || isequal(sCountryName, "IRELAND") || isequal(sCountryName, "ITALY")...
   || isequal(sCountryName, "JAPAN") || isequal(sCountryName, "NETHERLANDS")...
   || isequal(sCountryName, "NEWZEALAND") || isequal(sCountryName, "NORWAY")...
   || isequal(sCountryName, "SINGAPORE") || isequal(sCountryName, "SPAIN")...
   || isequal(sCountryName, "SWEDEN") || isequal(sCountryName, "SWITZERLAND")
    sMarket = "DM";
elseif isequal(sCountryName, "GREECE")...
       || isequal(sCountryName, "ISRAEL") || isequal(sCountryName, "PORTUGAL")
    sMarket = "DM/EM";
else
    sMarket = "EM";
end
end

