function [sMarket] = fMSCImarket(sCountryName)
%% MSCI MARKET
% Functions sorts whether the country is listet by the MSCI as emerging
% (EM) oder developed market (DM).
%% REQUIRES
% string with the name of the country
%% RETURNS
% string with the abbreviation of the market to which the country belongs
%% FUNCTION
% if-clause checking to which market the country belongs to using the
% country name string as described by Ball et al. (2016)
if isequal(sCountryName, "Australia") || isequal(sCountryName, "Austria")...
   || isequal(sCountryName, "Belgium") || isequal(sCountryName, "Canada")...
   || isequal(sCountryName, "Denmark") || isequal(sCountryName, "Finland")...
   || isequal(sCountryName, "France") || isequal(sCountryName, "Germany")...
   || isequal(sCountryName, "Great Britain") || isequal(sCountryName, "Hong Kong")...
   || isequal(sCountryName, "Ireland") || isequal(sCountryName, "Italy")...
   || isequal(sCountryName, "Japan") || isequal(sCountryName, "Netherlands")...
   || isequal(sCountryName, "New Zealand") || isequal(sCountryName, "Norway")...
   || isequal(sCountryName, "Singapore") || isequal(sCountryName, "Spain")...
   || isequal(sCountryName, "Sweden") || isequal(sCountryName, "Switzerland")
    sMarket = "DM";
elseif isequal(sCountryName, "Greece")...
       || isequal(sCountryName, "Israel") || isequal(sCountryName, "Portugal")
    sMarket = "DM/EM";
else
    sMarket = "EM";
end
end

